version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres:15rc1-alpine
    container_name: pg-database-crm-demo
    healthcheck:
      test: database_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "54325:5432"
    environment:
      POSTGRES_USER: onclick
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: crm_demo
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: false